Fix build of lkvm tool for MIPS
Source: Cavium Networks, Inc.
MR: 12750
Type: Defect Fix
Disposition: Needs submitting to PaX
ChangeID: 44b87c58ccab6d47e458a46086aeb6c22d9c9041
Description:

Since commit

 commit 93b125503ce3bd1c79dd6c94dececab07902778b
 Author: Corey Minyard <cminyard@mvista.com>
 Date:   Mon Jul 29 15:26:08 2013 -0500

    pax: start at pax-linux-3.10.3-test5.patch

    Source: http://www.grsecurity.net
    MR: 7111
    Type: Integration
    Disposition: Merged from http://www.grsecurity.net
    ChangeID: 20aa8e1cc8882d6c45b02a86e0e59eb373e6e064
    Description:

    Signed-off-by: Corey Minyard <cminyard@mvista.com>

it's not possible to build kvm tool, e.g. on x86:

 In file included from ../../include/uapi/linux/byteorder/little_endian.h:12:0,
                  from ../../arch/x86/include/uapi/asm/byteorder.h:4,
                  from include/linux/byteorder.h:4,
                  from include/kvm/ioport.h:12,
                  from builtin-run.c:19:
 ../../include/uapi/linux/swab.h:46:38: error: expected declaration specifiers or ‘...’ before ‘-’ token
 ../../include/uapi/linux/swab.h:57:38: error: expected declaration specifiers or ‘...’ before ‘-’ token
 ../../include/uapi/linux/swab.h:68:38: error: expected declaration specifiers or ‘...’ before ‘-’ token
 ...
 In file included from ../../arch/x86/include/uapi/asm/byteorder.h:4:0,
                  from include/linux/byteorder.h:4,
                  from include/kvm/ioport.h:12,
                  from builtin-run.c:19:
 ../../include/uapi/linux/byteorder/little_endian.h: At top level:
 ../../include/uapi/linux/byteorder/little_endian.h:47:44: error: expected declaration specifiers or ‘...’ before ‘-’ token
 ../../include/uapi/linux/byteorder/little_endian.h:79:44: error: expected declaration specifiers or ‘...’ before ‘-’ token
 ...
 In file included from builtin-run.c:39:0:
 ../../include/linux/err.h: At top level:
 ../../include/linux/err.h:22:58: error: expected declaration specifiers or ‘...’ before ‘-’ token
 ../../include/linux/err.h:27:56: error: expected declaration specifiers or ‘...’ before ‘-’ token
 ...

Similar errors show up when trying to build lkvm tool for MIPS (for
-march=octeon3).

Fix this by adding definition for __intentional_overflow to
tools/kvm/include/linux/compiler.h.

Signed-off-by: Andreas Herrmann <andreas.herrmann@caviumnetworks.com>
Signed-off-by: Corey Minyard <cminyard@mvista.com>